import type {
  Transaction,
  Goal,
  Investment,
  MonthlyData,
  CategoryBreakdown,
} from "@/types/financial"

export const mockTransactions: Transaction[] = [
  {
    id: "1",
    user_id: "user-1",
    type: "entrada",
    category: "fixo",
    amount: 8500,
    date: "2026-02-01",
    description: "Salario",
  },
  {
    id: "2",
    user_id: "user-1",
    type: "entrada",
    category: "variavel",
    amount: 1200,
    date: "2026-02-05",
    description: "Freelance - Projeto Web",
  },
  {
    id: "3",
    user_id: "user-1",
    type: "saida",
    category: "fixo",
    amount: 1800,
    date: "2026-02-03",
    description: "Aluguel",
  },
  {
    id: "4",
    user_id: "user-1",
    type: "saida",
    category: "fixo",
    amount: 450,
    date: "2026-02-05",
    description: "Conta de luz + agua + internet",
  },
  {
    id: "5",
    user_id: "user-1",
    type: "saida",
    category: "variavel",
    amount: 320,
    date: "2026-02-07",
    description: "Supermercado",
  },
  {
    id: "6",
    user_id: "user-1",
    type: "saida",
    category: "variavel",
    amount: 180,
    date: "2026-02-10",
    description: "Restaurante e delivery",
  },
  {
    id: "7",
    user_id: "user-1",
    type: "saida",
    category: "variavel",
    amount: 250,
    date: "2026-02-12",
    description: "Transporte / Combustivel",
  },
  {
    id: "8",
    user_id: "user-1",
    type: "saida",
    category: "investimento",
    amount: 2000,
    date: "2026-02-15",
    description: "Aporte mensal - CDB",
  },
  {
    id: "9",
    user_id: "user-1",
    type: "saida",
    category: "emergencia",
    amount: 500,
    date: "2026-02-15",
    description: "Reserva de emergencia",
  },
  {
    id: "10",
    user_id: "user-1",
    type: "saida",
    category: "meta",
    amount: 800,
    date: "2026-02-15",
    description: "Meta - Viagem Europa",
  },
  {
    id: "11",
    user_id: "user-1",
    type: "saida",
    category: "variavel",
    amount: 150,
    date: "2026-02-18",
    description: "Lazer - Cinema e jogos",
  },
  {
    id: "12",
    user_id: "user-1",
    type: "entrada",
    category: "variavel",
    amount: 350,
    date: "2026-02-20",
    description: "Cashback e dividendos",
  },
]

export const mockGoals: Goal[] = [
  {
    id: "1",
    user_id: "user-1",
    title: "Viagem Europa",
    target_amount: 25000,
    current_amount: 12500,
    deadline: "2026-12-31",
    category: "viagem",
  },
  {
    id: "2",
    user_id: "user-1",
    title: "MacBook Pro",
    target_amount: 18000,
    current_amount: 14400,
    deadline: "2026-06-30",
    category: "tecnologia",
  },
  {
    id: "3",
    user_id: "user-1",
    title: "Curso MBA",
    target_amount: 35000,
    current_amount: 8750,
    deadline: "2027-03-01",
    category: "educacao",
  },
  {
    id: "4",
    user_id: "user-1",
    title: "Entrada do Apartamento",
    target_amount: 100000,
    current_amount: 32000,
    deadline: "2028-01-01",
    category: "imovel",
  },
]

export const mockInvestments: Investment[] = [
  {
    id: "1",
    user_id: "user-1",
    name: "CDB Banco Inter",
    type: "renda_fixa",
    amount: 15000,
    return_rate: 13.5,
    date: "2025-06-01",
  },
  {
    id: "2",
    user_id: "user-1",
    name: "Tesouro IPCA+ 2029",
    type: "renda_fixa",
    amount: 10000,
    return_rate: 11.2,
    date: "2025-01-15",
  },
  {
    id: "3",
    user_id: "user-1",
    name: "IVVB11 - ETF S&P500",
    type: "renda_variavel",
    amount: 8500,
    return_rate: 18.3,
    date: "2025-03-10",
  },
  {
    id: "4",
    user_id: "user-1",
    name: "Bitcoin",
    type: "cripto",
    amount: 5000,
    return_rate: 42.1,
    date: "2025-08-20",
  },
  {
    id: "5",
    user_id: "user-1",
    name: "Fundo Multi XP",
    type: "fundo",
    amount: 6500,
    return_rate: 9.8,
    date: "2025-04-05",
  },
]

export const mockMonthlyData: MonthlyData[] = [
  { month: "Set", receitas: 8200, gastos: 5100, investimentos: 1800, reserva: 15000 },
  { month: "Out", receitas: 8500, gastos: 5400, investimentos: 2000, reserva: 17500 },
  { month: "Nov", receitas: 9100, gastos: 5800, investimentos: 2000, reserva: 20000 },
  { month: "Dez", receitas: 12000, gastos: 7200, investimentos: 2500, reserva: 22500 },
  { month: "Jan", receitas: 8500, gastos: 4900, investimentos: 2000, reserva: 25000 },
  { month: "Fev", receitas: 10050, gastos: 6450, investimentos: 2000, reserva: 27500 },
]

export const mockCategoryBreakdown: CategoryBreakdown[] = [
  { name: "Moradia", value: 1800, color: "var(--chart-1)" },
  { name: "Alimentacao", value: 500, color: "var(--chart-2)" },
  { name: "Transporte", value: 250, color: "var(--chart-3)" },
  { name: "Investimentos", value: 2000, color: "var(--chart-4)" },
  { name: "Lazer", value: 330, color: "var(--chart-5)" },
  { name: "Reserva", value: 500, color: "var(--color-primary)" },
  { name: "Metas", value: 800, color: "var(--color-accent)" },
]

export const currentMonthSummary = {
  receitas: 10050,
  gastos: 6450,
  saldo: 3600,
  investido: 45000,
  reserva: 27500,
  metasTotal: 67650,
  receitasAnterior: 8500,
  gastosAnterior: 4900,
  investidoAnterior: 43000,
  reservaAnterior: 25000,
}
